#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'go2-bridge','console_scripts','lidar_bridge'
__requires__ = 'go2-bridge'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('go2-bridge', 'console_scripts', 'lidar_bridge')()
    )
